# Generated by Django 3.2.9 on 2021-11-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faceapp', '0002_auto_20211112_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='emotion',
            name='content_str',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emotion',
            name='emotion_dt',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
