# Generated by Django 3.2.9 on 2021-11-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faceapp', '0003_auto_20211116_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='content_str',
        ),
    ]
