# Generated by Django 3.1.6 on 2021-11-16 06:54

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Faceapp', '0004_remove_emotion_content_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='url',
        ),
        migrations.AddField(
            model_name='emotion',
            name='content_str',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='emotion_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emotion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
