# Generated by Django 3.1.6 on 2021-11-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faceapp', '0005_auto_20211116_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
