# Generated by Django 3.1.6 on 2021-11-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faceapp', '0006_emotion_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordcloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
