# Generated by Django 3.1.6 on 2021-11-17 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Faceapp', '0007_wordcloud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wordcloud',
        ),
        migrations.AddField(
            model_name='emotion',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
